title: Ekaterina Noskova
description: personal page
remote_theme: noscode/minima_reboot
footer_icons:
  - username: noscode
    url: https://github.com/noscode
    icon: https://github.com/jekyll/minima/tree/master/assets/minima-social-icons.svg#github
